# Use an official Python runtime as a parent image
FROM python:3.12-slim

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Run app.py when the container launches
ENTRYPOINT ["invoke", "serve-dev"]

